# Traefik configuration file
global:
  checkNewVersion: true
  sendAnonymousUsage: false

# Entrypoints configuration
entryPoints:
  web:
    address: "0.0.0.0:80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https

  websecure:
    address: "0.0.0.0:443"

# Let's Encrypt configuration
certificatesResolvers:
  letsencrypt:
    acme:
      email: "valevalevale@vrensk.com"  # Email for Let's Encrypt notifications
      storage: "/etc/traefik/acme.json"
      httpChallenge:
        entryPoint: web
      preferredChain: "ISRG Root X1"  # Use Let's Encrypt's preferred chain

# API and Dashboard configuration (optional, for monitoring)
api:
  dashboard: true
  insecure: false  # Set to true only for testing

# Logging configuration
log:
  level: INFO  # DEBUG, INFO, WARN, ERROR, FATAL, PANIC

# Access log configuration
accessLog:
  filePath: "/var/log/traefik/access.log"
  bufferingSize: 100

# HTTP configuration
http:
  routers:
    api:
      rule: "Host(`backend.ai4devs.valevalevale.es`)"
      service: "api"
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt

  services:
    api:
      loadBalancer:
        servers:
          - url: "http://localhost:3010"  # Your Node.js application

# File provider for dynamic configuration
providers:
  file:
    directory: "/etc/traefik/dynamic"
    watch: true
