# Traefik configuration file
global:
  checkNewVersion: true
  sendAnonymousUsage: false

# Entrypoints configuration
entryPoints:
  web:
    address: "0.0.0.0:80"

  websecure:
    address: "0.0.0.0:443"

# Let's Encrypt configuration
certificatesResolvers:
  letsencrypt:
    acme:
      email: "valevalevale@vrensk.com"  # Email for Let's Encrypt notifications
      storage: "/etc/traefik/acme.json"
      httpChallenge:
        entryPoint: web
      preferredChain: "ISRG Root X1"  # Use Let's Encrypt's preferred chain

# API and Dashboard configuration (optional, for monitoring)
api:
  dashboard: true
  insecure: false  # Set to true only for testing

# Logging configuration
log:
  level: INFO  # DEBUG, INFO, WARN, ERROR, FATAL, PANIC

# Access log configuration
accessLog:
  filePath: "/var/log/traefik/access.log"
  bufferingSize: 100

# HTTP configuration
http:
  routers:
    # Add explicit redirect for non-ACME paths
    web-to-websecure:
      rule: "Host(`backend.ai4devs.valevalevale.es`) && !PathPrefix(`/.well-known/acme-challenge/`)"
      entryPoints:
        - web
      middlewares:
        - redirect-to-https
      service: noop@internal

    # Keep the ACME challenge router
    acme-http:
      rule: "PathPrefix(`/.well-known/acme-challenge/`)"
      entryPoints:
        - web
      service: acme-http@internal

    # Your API router
    api:
      rule: "Host(`backend.ai4devs.valevalevale.es`)"
      service: "api"
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt

  middlewares:
    redirect-to-https:
      redirectScheme:
        scheme: https
        permanent: true

  services:
    api:
      loadBalancer:
        servers:
          - url: "http://localhost:3010"  # Your Node.js application

# File provider for dynamic configuration
providers:
  file:
    directory: "/etc/traefik/dynamic"
    watch: true
