# Traefik configuration file
global:
  checkNewVersion: true
  sendAnonymousUsage: false

# Entrypoints configuration
entryPoints:
  web:
    address: "0.0.0.0:80"

  websecure:
    address: "0.0.0.0:443"
    http:
      tls:
        certResolver: letsencrypt

# Let's Encrypt configuration
certificatesResolvers:
  letsencrypt:
    acme:
      email: "valevalevale@vrensk.com"
      storage: "/etc/traefik/acme.json"
      httpChallenge:
        entryPoint: web

# API and Dashboard configuration (optional, for monitoring)
api:
  dashboard: true
  insecure: false  # Set to true only for testing

# Logging configuration
log:
  level: DEBUG  # DEBUG, INFO, WARN, ERROR, FATAL, PANIC

# Access log configuration
accessLog:
  filePath: "/var/log/traefik/access.log"
  bufferingSize: 100

# HTTP configuration
http:
  routers:
    lti_ats-http:
      rule: "Host(`backend.ai4devs.valevalevale.es`)"
      service: "lti_ats"
      entryPoints:
        - web

    lti_ats:
      rule: "Host(`backend.ai4devs.valevalevale.es`)"
      service: "lti_ats"
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt

  services:
    lti_ats:
      loadBalancer:
        servers:
          - url: "http://localhost:3010"

# File provider for dynamic configuration
providers:
  file:
    directory: "/etc/traefik/dynamic"
    watch: true
